"""Render a results set into `leaderboard.md` (rescaled for the v0.1 task set)."""

from __future__ import annotations

from pathlib import Path
from statistics import mean
from typing import Any, Dict, List

from .conditions import CONDITION_INFO, CONDITION_ORDER
from .schema import Result
from .substrates import TASK_BEARING_STRATEGIES


def _pct(x: float) -> str:
    return f"{x * 100:.0f}%"


def _switch(x) -> str:
    return "n/a" if x is None else f"{x * 100:.0f}%"


def _breakdown(results: List[Result], keyfn, attr: str) -> Dict[Any, float]:
    buckets: Dict[Any, List[float]] = {}
    for r in results:
        buckets.setdefault(keyfn(r), []).append(1.0 if getattr(r, attr) else 0.0)
    return {k: mean(v) for k, v in buckets.items()}


def render_leaderboard(
    results_by_condition: Dict[str, List[Result]],
    metrics: Dict[str, Dict[str, Any]],
    *,
    solver_name: str,
    task_set: str,
) -> str:
    conditions = [c for c in CONDITION_ORDER if c in results_by_condition]
    n_tasks = len(results_by_condition[conditions[0]])
    difficulties = sorted({r.difficulty for r in results_by_condition[conditions[0]]})

    L: List[str] = []
    L.append("# substrate-bench leaderboard")
    L.append("")
    L.append(
        "**Thesis:** agents that *select* the right cognitive strategy beat agents "
        "that don't — and substrate-selection accuracy is the number that shows it. "
        "Read for the asymmetry on `language`/`social` tasks, where indiscriminate "
        "code use (condition C) is the wrong **strategy** and loses."
    )
    L.append("")
    L.append(f"- Solver: `{solver_name}`  ·  Task set: `{task_set}`  ·  Tasks: {n_tasks}")
    L.append("")

    # --- condition summary ---------------------------------------------------
    L.append("## Conditions")
    L.append("")
    L.append(
        "| Condition | Description | Substrate-sel. acc | Task acc | Composite | "
        "Mean cost ($) | Cost-adj acc | Switch (meta) | Verified | Audit pass |"
    )
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for c in conditions:
        m = metrics[c]
        name, desc = CONDITION_INFO[c]
        L.append(
            f"| **{c} · {name}** | {desc} | {_pct(m['substrate_selection_accuracy'])} | "
            f"{_pct(m['task_accuracy'])} | {m['composite']:.3f} | {m['mean_cost']:.6f} | "
            f"{m['cost_adjusted_accuracy']:.1f} | {_switch(m['switch_rate'])} | "
            f"{_pct(m['verified_rate'])} | {_pct(m['audit_pass_rate'])} |"
        )
    L.append("")
    L.append("*Composite = 0.6 × task accuracy + 0.4 × substrate-selection accuracy.*")
    L.append("")

    # --- substrate-selection accuracy by gold strategy -----------------------
    L.append("## Substrate-selection accuracy by gold strategy")
    L.append("")
    L.append("Declared strategy ∈ the task's gold set, broken out by the task's primary strategy.")
    L.append("")
    L.append("| Strategy | " + " | ".join(conditions) + " |")
    L.append("|" + "---|" * (len(conditions) + 1))
    strat_key = lambda r: r.gold_substrate[0]
    per_cond_strat = {c: _breakdown(results_by_condition[c], strat_key, "substrate_correct") for c in conditions}
    present = [s for s in TASK_BEARING_STRATEGIES if any(s in per_cond_strat[c] for c in conditions)]
    for s in present:
        cells = [(_pct(per_cond_strat[c][s]) if s in per_cond_strat[c] else "—") for c in conditions]
        L.append(f"| {s} | " + " | ".join(cells) + " |")
    L.append("")

    # --- task accuracy by difficulty (regime collapse) -----------------------
    L.append("## Task accuracy by difficulty")
    L.append("")
    L.append("Where the difficulty-regime collapse shows up (the Apple-paper effect).")
    L.append("")
    L.append("| Difficulty | " + " | ".join(conditions) + " |")
    L.append("|" + "---|" * (len(conditions) + 1))
    diff_key = lambda r: r.difficulty
    per_cond_diff = {c: _breakdown(results_by_condition[c], diff_key, "answer_correct") for c in conditions}
    for d in difficulties:
        cells = [(_pct(per_cond_diff[c][d]) if d in per_cond_diff[c] else "—") for c in conditions]
        L.append(f"| d{d} | " + " | ".join(cells) + " |")
    L.append("")

    L.append("---")
    L.append(
        "_Generated by `substrate-bench`. Numbers from the offline `stub` solver are "
        "illustrative of the instrument, not measured model performance; plug in a "
        "real provider for real numbers._"
    )
    L.append("")
    return "\n".join(L)


def write_leaderboard(
    path: str | Path,
    results_by_condition: Dict[str, List[Result]],
    metrics: Dict[str, Dict[str, Any]],
    *,
    solver_name: str,
    task_set: str,
) -> str:
    text = render_leaderboard(
        results_by_condition, metrics, solver_name=solver_name, task_set=task_set
    )
    Path(path).write_text(text, encoding="utf-8")
    return text
