"""Render a results set into `leaderboard.md`."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from .conditions import CONDITION_INFO, CONDITION_ORDER
from .schema import Result


def _fmt_pct(x: float) -> str:
    return f"{x * 100:.0f}%"


def _fmt_switch(x) -> str:
    return "n/a" if x is None else f"{x * 100:.0f}%"


def render_leaderboard(
    results_by_condition: Dict[str, List[Result]],
    metrics: Dict[str, Dict[str, Any]],
    *,
    solver_name: str,
    task_set: str,
) -> str:
    conditions = [c for c in CONDITION_ORDER if c in results_by_condition]
    any_results = results_by_condition[conditions[0]]
    tasks = [(r.task_id, "+".join(r.gold_substrate)) for r in any_results]

    lines: List[str] = []
    lines.append("# substrate-bench leaderboard")
    lines.append("")
    lines.append(
        "**Thesis:** agents that *select* the right computational substrate beat "
        "agents that don't — and substrate-selection accuracy is the number that "
        "shows it. The point to read for is the asymmetry on `language`/`social` "
        "tasks, where indiscriminate code use (condition C) **loses**."
    )
    lines.append("")
    lines.append(f"- Solver: `{solver_name}`  ·  Task set: `{task_set}`  ·  Tasks: {len(tasks)}")
    lines.append("")

    # --- condition summary ---------------------------------------------------
    lines.append("## Conditions")
    lines.append("")
    lines.append(
        "| Condition | Description | Substrate-sel. acc | Task acc | Composite | "
        "Mean cost ($) | Cost-adj acc | Switch rate (meta) | Verified |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for c in conditions:
        m = metrics[c]
        name, desc = CONDITION_INFO[c]
        lines.append(
            f"| **{c} · {name}** | {desc} | "
            f"{_fmt_pct(m['substrate_selection_accuracy'])} | "
            f"{_fmt_pct(m['task_accuracy'])} | "
            f"{m['composite']:.3f} | "
            f"{m['mean_cost']:.6f} | "
            f"{m['cost_adjusted_accuracy']:.1f} | "
            f"{_fmt_switch(m['switch_rate'])} | "
            f"{_fmt_pct(m['verified_rate'])} |"
        )
    lines.append("")
    lines.append("*Composite = 0.6 × task accuracy + 0.4 × substrate-selection accuracy.*")
    lines.append("")

    # --- per-task answer correctness ----------------------------------------
    def _grid(attr: str, title: str, note: str) -> None:
        lines.append(f"## {title}")
        lines.append("")
        lines.append(note)
        lines.append("")
        header = "| Task | gold | " + " | ".join(conditions) + " |"
        lines.append(header)
        lines.append("|" + "---|" * (len(conditions) + 2))
        by_task: Dict[str, Dict[str, Result]] = {}
        for c in conditions:
            for r in results_by_condition[c]:
                by_task.setdefault(r.task_id, {})[c] = r
        for tid, gold in tasks:
            cells = []
            for c in conditions:
                r = by_task[tid][c]
                ok = getattr(r, attr)
                cells.append("✓" if ok else "✗")
            lines.append(f"| {tid} | {gold} | " + " | ".join(cells) + " |")
        lines.append("")

    _grid(
        "answer_correct",
        "Per-task answer correctness",
        "✓ = the declared checker passed.",
    )
    _grid(
        "substrate_correct",
        "Per-task substrate selection",
        "✓ = the condition's chosen substrate was in the task's gold set. "
        "Note condition **C** failing the `language`/`social` tasks (lang-001, "
        "social-001) and `simulation`-only sim-001 — that is the whole argument.",
    )

    lines.append("---")
    lines.append(
        "_Generated by `substrate-bench`. Numbers from the offline `stub` solver "
        "are illustrative of the instrument, not measured model performance; "
        "plug in a real provider to get real numbers._"
    )
    lines.append("")
    return "\n".join(lines)


def write_leaderboard(
    path: str | Path,
    results_by_condition: Dict[str, List[Result]],
    metrics: Dict[str, Dict[str, Any]],
    *,
    solver_name: str,
    task_set: str,
) -> str:
    text = render_leaderboard(
        results_by_condition, metrics, solver_name=solver_name, task_set=task_set
    )
    Path(path).write_text(text, encoding="utf-8")
    return text
